### ISSUE TITLE
Remove 8px colstart offset

### ISSUE THREAD

**Issue by chimok** [adafruit/Adafruit_CircuitPython_SSD1680#27]
Hello, 

I have a WeAct 2.9 Epaper Display, it works well with this driver.

But on the top of the screen there was always some random b/w noise visible. I read omewhere the hint to set `colstart=8` to fix some issues. But it didn't change anything.

I want to understand if Partial Update is possible with this driver, so i read the source code and found this here:
https://github.com/adafruit/Adafruit_CircuitPython_SSD1680/blob/main/adafruit_ssd1680.py#L76

Without colstart, there is colstart=8 set. This magic causing the issues with my display!
I set `colstart=0` and everything was fine.

So I'm wondering isn't it better to remove this default and only add this to docs?

**Edit:** Found now the PR, still believe its wrong to set a value that works for the majority of displays: https://github.com/adafruit/Adafruit_CircuitPython_SSD1680/issues/5

**Comment by tannewt** [comment]
It is expected that you'll need to tweak `colstart`, `rowstart`, `height` and `width` for a given display because it depends on how the display is connected to the SSD1680. The SSD1680 can be connected to the actual display in a variety of ways. I think it is fine to have a default that doesn't work for everything.

Instead of removing the default, I'd suggest you add an example for this particular display. Examples are the best place to start since they can capture specific display settings.
